CREATE TABLE match (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_time TIMESTAMP NOT NULL,
    match_map VARCHAR(255) NOT NULL,
    map_type VARCHAR(255) NOT NULL,
    match_mode VARCHAR(255) NOT NULL,
    match_result VARCHAR(255) NOT NULL,
    match_score VARCHAR(255) NOT NULL,
    total_duration NUMERIC(21, 0) NOT NULL
)