CREATE TABLE performance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id BIGINT NOT NULL REFERENCES match(id),
    hero_id BIGINT NOT NULL REFERENCES hero(id),
    hero_order INT NOT NULL,
    time_played NUMERIC(21, 0) NOT NULL,
    eliminations INT NOT NULL,
    assists INT NOT NULL,
    deaths INT NOT NULL,
    damage_dealt INT NOT NULL,
    healing_done INT NOT NULL,
    damage_mitigated INT NOT NULL,
    UNIQUE (match_id, hero_id, hero_order)
)